services:
  - type: web
    name: streamfetch-api
    runtime: node
    region: oregon
    plan: free
    rootDir: .
    buildCommand: bash render-build.sh
    startCommand: node artifacts/api-server/dist/index.cjs
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: YTDLP_PATH
        value: /usr/local/bin/yt-dlp
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: NOWPAYMENTS_API_KEY
        sync: false
      - key: ALLOWED_ORIGIN
        sync: false
