directories:
  output: dist-app
  buildResources: build
appId: com.ytsave.desktop
productName: YTSave
copyright: Copyright © 2025 YTSave
files:
  - filter:
      - dist/**/*
      - package.json
extraResources:
  - from: ../api-server/dist
    to: artifacts/api-server/dist
    filter:
      - '**/*'
  - from: ../api-server/package.json
    to: artifacts/api-server/package.json
  - from: ../streamfetch/dist
    to: artifacts/streamfetch/dist
    filter:
      - '**/*'
win:
  target:
    - target: nsis
      arch:
        - x64
  icon: build/icons/256x256.png
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: YTSave
mac:
  target:
    - target: dmg
      arch:
        - x64
        - arm64
  icon: build/icons/512x512.png
  category: public.app-category.utilities
  darkModeSupport: true
linux:
  target:
    - target: AppImage
      arch:
        - x64
  icon: build/icons
  category: Utility
publish: null
electronVersion: 36.9.5
